from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from one_ball import Ui_Dialog as OneBallDialog
from two_ball import Ui_Dialog as TwoBallDialog
from max_ball import Ui_Dialog as MaxBallDialog
from zero_ball import Ui_Dialog as ZeroBallDialog

class Ui_Dialog(object):
    def setupUi(self, Dialog, main_dialog):
        Dialog.setObjectName("Dialog")
        self.dialog = Dialog  # Сохраняем ссылку на диалог
        self.main_dialog = main_dialog  # Сохраняем ссылку на основной диалог
        Dialog.resize(800, 800)
        Dialog.setStyleSheet("background-color: rgb(36, 31, 49);")
        self.frame_4 = QtWidgets.QFrame(Dialog)
        self.frame_4.setGeometry(QtCore.QRect(0, 0, 801, 731))
        self.frame_4.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.frame_5 = QtWidgets.QFrame(self.frame_4)
        self.frame_5.setGeometry(QtCore.QRect(0, 120, 801, 611))
        self.frame_5.setAutoFillBackground(False)
        self.frame_5.setStyleSheet("background-color: rgb(119, 118, 123);")
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.label_14 = QtWidgets.QLabel(self.frame_5)
        self.label_14.setGeometry(QtCore.QRect(10, 0, 781, 61))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        font.setPointSize(13)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.pushButton_6 = QtWidgets.QPushButton(self.frame_5)
        self.pushButton_6.setGeometry(QtCore.QRect(690, 570, 87, 27))
        self.pushButton_6.setStyleSheet("background-color: rgb(28, 113, 216);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.label_13 = QtWidgets.QLabel(self.frame_5)
        self.label_13.setGeometry(QtCore.QRect(60, 50, 371, 141))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.change2 = QtWidgets.QComboBox(self.frame_5)
        self.change2.setGeometry(QtCore.QRect(80, 146, 121, 20))
        self.change2.setObjectName("change2")
        self.change2.addItem("")
        self.change2.addItem("")
        self.change2.addItem("")
        self.change2.addItem("")
        self.label_15 = QtWidgets.QLabel(self.frame_5)
        self.label_15.setGeometry(QtCore.QRect(10, 190, 781, 61))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        font.setPointSize(13)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_31 = QtWidgets.QLabel(self.frame_5)
        self.label_31.setGeometry(QtCore.QRect(60, 250, 241, 161))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.comboBox_2 = QtWidgets.QComboBox(self.frame_5)
        self.comboBox_2.setGeometry(QtCore.QRect(130, 300, 101, 20))
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.label_16 = QtWidgets.QLabel(self.frame_5)
        self.label_16.setGeometry(QtCore.QRect(10, 410, 781, 51))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        font.setPointSize(13)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_27 = QtWidgets.QLabel(self.frame_5)
        self.label_27.setGeometry(QtCore.QRect(30, 460, 231, 31))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        self.label_27.setFont(font)
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.frame_5)
        self.label_28.setGeometry(QtCore.QRect(30, 490, 231, 21))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        self.label_28.setFont(font)
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.frame_5)
        self.label_29.setGeometry(QtCore.QRect(30, 510, 291, 31))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        self.label_29.setFont(font)
        self.label_29.setObjectName("label_29")
        self.label_30 = QtWidgets.QLabel(self.frame_5)
        self.label_30.setGeometry(QtCore.QRect(30, 540, 261, 21))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        self.label_30.setFont(font)
        self.label_30.setObjectName("label_30")
        self.radioButton = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton.setGeometry(QtCore.QRect(10, 460, 16, 31))
        self.radioButton.setStyleSheet("color: rgb(224, 27, 36);")
        self.radioButton.setText("")
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_2.setGeometry(QtCore.QRect(9, 490, 21, 21))
        self.radioButton_2.setStyleSheet("color: rgb(224, 27, 36);")
        self.radioButton_2.setText("")
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_3.setGeometry(QtCore.QRect(10, 510, 16, 31))
        self.radioButton_3.setStyleSheet("color: rgb(224, 27, 36);")
        self.radioButton_3.setText("")
        self.radioButton_3.setObjectName("radioButton_3")
        self.radioButton_4 = QtWidgets.QRadioButton(self.frame_5)
        self.radioButton_4.setGeometry(QtCore.QRect(10, 540, 16, 21))
        self.radioButton_4.setStyleSheet("color: rgb(224, 27, 36);")
        self.radioButton_4.setText("")
        self.radioButton_4.setObjectName("radioButton_4")
        self.frame_6 = QtWidgets.QFrame(self.frame_4)
        self.frame_6.setGeometry(QtCore.QRect(0, 70, 801, 51))
        self.frame_6.setStyleSheet("background-color: rgb(224, 27, 36);")
        self.frame_6.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.label_24 = QtWidgets.QLabel(self.frame_6)
        self.label_24.setGeometry(QtCore.QRect(10, 20, 211, 19))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_24.setFont(font)
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(self.frame_6)
        self.label_25.setGeometry(QtCore.QRect(740, 10, 66, 31))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_25.setFont(font)
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.frame_4)
        self.label_26.setGeometry(QtCore.QRect(10, 20, 301, 41))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_26.setFont(font)
        self.label_26.setObjectName("label_26")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(310, 740, 171, 41))
        self.pushButton.clicked.connect(Dialog.reject)  # Закрываем текущее окно
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Обучающая система"))
        self.label_14.setText(_translate("Dialog", "1.  У вас есть следующий код для реализации стека. Какой из следующих вариантов \n"
"правильно завершает функцию push, чтобы добавить элемент на вершину стека?"))
        self.pushButton_6.setText(_translate("Dialog", "Ответить"))
        self.label_13.setText(_translate("Dialog", "void push(Node **top, int d) {\n"
"    Node *pv = new Node;\n"
"    pv->d = d;\n"
"    pv->p = *top;\n"
"                             ; // Дополните эту строку\n"
"}"))
        self.change2.setItemText(0, _translate("Dialog", "pv->p = 0"))
        self.change2.setItemText(1, _translate("Dialog", "*top = pv"))
        self.change2.setItemText(2, _translate("Dialog", "pv->d = *top"))
        self.change2.setItemText(3, _translate("Dialog", "*top = pv->p"))
        self.label_15.setText(_translate("Dialog", "2. Дополните следующий код, выбрав правильный вариант, чтобы функция strlen \n"
"корректно подсчитывала длину строки."))
        self.label_31.setText(_translate("Dialog", "int strlen(char* p) {\n"
"    int i = 0;\n"
"    while (                    ) {\n"
"        i++;\n"
"    }\n"
"    return i;\n"
"}"))
        self.comboBox_2.setItemText(0, _translate("Dialog", "*p[i] != \'\\0\'"))
        self.comboBox_2.setItemText(1, _translate("Dialog", "p != \'\\0\'"))
        self.comboBox_2.setItemText(2, _translate("Dialog", "p[i] != \'\\0\'"))
        self.comboBox_2.setItemText(3, _translate("Dialog", "*p != 0"))
        self.label_16.setText(_translate("Dialog", "3. Какой из следующих фрагментов кода будет выполняться как минимум один раз, \n"
"если переменная x равна 0?"))
        self.label_27.setText(_translate("Dialog", "A) while (x > 0) { cout << x; }"))
        self.label_28.setText(_translate("Dialog", "B) while (x < 0) { cout << x; }"))
        self.label_29.setText(_translate("Dialog", "C) do { cout << x; } while (x > 0);"))
        self.label_30.setText(_translate("Dialog", "D) do { cout << x; } while (x < 0);"))
        self.label_24.setText(_translate("Dialog", "Условие заданий"))
        self.label_25.setText(_translate("Dialog", "5Б"))
        self.label_26.setText(_translate("Dialog", "4. Работа с кодом"))
        self.pushButton.setText(_translate("Dialog", "Вернуться на главную"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())