from PyQt5 import QtCore, QtGui, QtWidgets
import sys
from one_ball import Ui_Dialog as OneBallDialog
from max_ball import Ui_Dialog as MaxBallDialog
from zero_ball import Ui_Dialog as ZeroBallDialog

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(800, 600)
        Dialog.setStyleSheet("background-color: rgb(36, 31, 49);")
        self.frame_3 = QtWidgets.QFrame(Dialog)
        self.frame_3.setGeometry(QtCore.QRect(0, 0, 801, 491))
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.frame_2 = QtWidgets.QFrame(self.frame_3)
        self.frame_2.setGeometry(QtCore.QRect(0, 120, 801, 371))
        self.frame_2.setAutoFillBackground(False)
        self.frame_2.setStyleSheet("background-color: rgb(119, 118, 123);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_3 = QtWidgets.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(0, 0, 711, 61))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_5 = QtWidgets.QLabel(self.frame_2)
        self.label_5.setGeometry(QtCore.QRect(50, 70, 461, 31))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame_2)
        self.label_6.setGeometry(QtCore.QRect(50, 100, 371, 19))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.frame_2)
        self.label_7.setGeometry(QtCore.QRect(50, 120, 421, 31))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_4 = QtWidgets.QLabel(self.frame_2)
        self.label_4.setGeometry(QtCore.QRect(10, 150, 751, 61))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.frame_2)
        self.label_8.setGeometry(QtCore.QRect(50, 208, 66, 21))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.frame_2)
        self.label_9.setGeometry(QtCore.QRect(50, 230, 66, 31))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.frame_2)
        self.label_10.setGeometry(QtCore.QRect(50, 260, 81, 21))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.frame_2)
        self.label_11.setGeometry(QtCore.QRect(50, 290, 81, 21))
        self.label_11.setObjectName("label_11")
        self.pushButton_4 = QtWidgets.QPushButton(self.frame_2)
        self.pushButton_4.setGeometry(QtCore.QRect(680, 330, 87, 27))
        self.pushButton_4.setStyleSheet("background-color: rgb(28, 113, 216);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_4.clicked.connect(self.check_answers)  # Подключаем кнопку к функции проверки ответов
        self.AnswerA_2 = QtWidgets.QCheckBox(self.frame_2)
        self.AnswerA_2.setGeometry(QtCore.QRect(30, 204, 20, 31))
        self.AnswerA_2.setStyleSheet("color: rgb(224, 27, 36);")
        self.AnswerA_2.setText("")
        self.AnswerA_2.setObjectName("AnswerA_2")
        self.AnswerC_2 = QtWidgets.QCheckBox(self.frame_2)
        self.AnswerC_2.setGeometry(QtCore.QRect(30, 250, 20, 41))
        self.AnswerC_2.setStyleSheet("color: rgb(224, 27, 36);")
        self.AnswerC_2.setText("")
        self.AnswerC_2.setObjectName("AnswerC_2")
        self.AnswerD_2 = QtWidgets.QCheckBox(self.frame_2)
        self.AnswerD_2.setGeometry(QtCore.QRect(30, 280, 20, 41))
        self.AnswerD_2.setStyleSheet("color: rgb(224, 27, 36);")
        self.AnswerD_2.setText("")
        self.AnswerD_2.setObjectName("AnswerD_2")
        self.AnswerB_2 = QtWidgets.QCheckBox(self.frame_2)
        self.AnswerB_2.setGeometry(QtCore.QRect(30, 230, 20, 31))
        self.AnswerB_2.setStyleSheet("color: rgb(224, 27, 36);")
        self.AnswerB_2.setText("")
        self.AnswerB_2.setObjectName("AnswerB_2")
        self.AnswerD = QtWidgets.QCheckBox(self.frame_2)
        self.AnswerD.setGeometry(QtCore.QRect(30, 120, 20, 31))
        self.AnswerD.setStyleSheet("color: rgb(224, 27, 36);")
        self.AnswerD.setText("")
        self.AnswerD.setObjectName("AnswerD")
        self.AnswerB = QtWidgets.QCheckBox(self.frame_2)
        self.AnswerB.setGeometry(QtCore.QRect(30, 70, 20, 31))
        self.AnswerB.setStyleSheet("color: rgb(224, 27, 36);")
        self.AnswerB.setText("")
        self.AnswerB.setObjectName("AnswerB")
        self.AnswerC = QtWidgets.QCheckBox(self.frame_2)
        self.AnswerC.setGeometry(QtCore.QRect(30, 100, 20, 21))
        self.AnswerC.setStyleSheet("color: rgb(224, 27, 36);")
        self.AnswerC.setText("")
        self.AnswerC.setObjectName("AnswerC")
        self.label_13 = QtWidgets.QLabel(self.frame_2)
        self.label_13.setGeometry(QtCore.QRect(50, 50, 461, 19))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.AnswerA = QtWidgets.QCheckBox(self.frame_2)
        self.AnswerA.setGeometry(QtCore.QRect(30, 50, 20, 21))
        self.AnswerA.setStyleSheet("color: rgb(224, 27, 36);")
        self.AnswerA.setText("")
        self.AnswerA.setObjectName("AnswerA")
        self.frame = QtWidgets.QFrame(self.frame_3)
        self.frame.setGeometry(QtCore.QRect(0, 70, 801, 51))
        self.frame.setStyleSheet("background-color: rgb(224, 27, 36);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 20, 211, 19))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_12 = QtWidgets.QLabel(self.frame)
        self.label_12.setGeometry(QtCore.QRect(730, 0, 66, 51))
        font = QtGui.QFont()
        font.setFamily("Serif")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_2 = QtWidgets.QLabel(self.frame_3)
        self.label_2.setGeometry(QtCore.QRect(10, 20, 491, 41))
        font = QtGui.QFont()
        font.setFamily("LM Roman 8")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(Dialog)
        self.pushButton.setGeometry(QtCore.QRect(320, 530, 171, 41))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(630, 530, 151, 41))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(20, 530, 161, 41))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def check_answers(self):
        score = 0

        # Проверяем первый вопрос
        if self.AnswerB.isChecked():  # Правильный ответ B
            score += 1
        
        # Проверяем второй вопрос
        if self.AnswerC_2.isChecked():  # Правильный ответ C
            score += 1

        # Открываем соответствующее окно в зависимости от набранных баллов
        if score == 2:
            self.show_result(MaxBallDialog)
        elif score == 1:
            self.show_result(OneBallDialog)
        else:
            self.show_result(ZeroBallDialog)

    def show_result(self, dialog_class):
        self.result_dialog = QtWidgets.QDialog()
        self.result_ui = dialog_class()
        self.result_ui.setupUi(self.result_dialog)
        self.result_dialog.exec_()

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Обучающая система"))
        self.label_3.setText(_translate("Dialog", "1.  Что такое область видимости имени в программе? "))
        self.label_5.setText(_translate("Dialog", "B) Часть программы, где имя может быть использовано"))
        self.label_6.setText(_translate("Dialog", "C) Место, где имя может быть использовано"))
        self.label_7.setText(_translate("Dialog", "D) Область памяти, выделенная для переменной"))
        self.label_4.setText(_translate("Dialog", "2.  Какой оператор используется для разветвления процесса вычислений на \n"
"несколько направлений в C++?"))
        self.label_8.setText(_translate("Dialog", "A) for"))
        self.label_9.setText(_translate("Dialog", "B) while"))
        self.label_10.setText(_translate("Dialog", "C) switch"))
        self.label_11.setText(_translate("Dialog", "D) do while"))
        self.pushButton_4.setText(_translate("Dialog", "Ответить"))
        self.label_13.setText(_translate("Dialog", "A) Время, в течение которого имя существует в памяти"))
        self.label.setText(_translate("Dialog", "Условие заданий"))
        self.label_12.setText(_translate("Dialog", "2Б"))
        self.label_2.setText(_translate("Dialog", "1. Вопросы легкой сложности"))
        self.pushButton.setText(_translate("Dialog", "Вернуться на главную"))
        self.pushButton_2.setText(_translate("Dialog", "Следующий вопрос"))
        self.pushButton_3.setText(_translate("Dialog", "Предыдущая теория"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
